apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels: 
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: peaonunes/docker-demo-node
    ports:
    - name: nodejs-port
      containerPort: 3000
